name: "Build flake outputs"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v3
    - name: "Install Nix"
      uses: cachix/install-nix-action@v20
      with:
          nix_path: nixpkgs=channel:nixos-unstable
    - name: "Install Cachix"
      uses: cachix/cachix-action@v12
      with:
          name: powder-day
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "Build NixOS Configuration"
      run: nix build .#nixosConfigurations.deck.config.system.build.toplevel; cachix push result
